import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import { mega } from '../functions/mega'
import Numero from '../components/Numero'

export default function Home() {

  const [qtd, setQtd] = useState(6)
  const [numbers, setNumbers] = useState([])
  
  useEffect(()=>{
    setNumbers(mega())
  },[])

  function renderizar(numbers) {
    return(
      <div style={{
        display: 'flex',
        flexWrap: 'wrap'
      }}>
        {numbers.map((e,i)=><Numero key={i} numero={e}/>)}
      </div>
    )
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <h1>Mega Sena</h1>
          {renderizar(numbers)}
          <input type="number" min={6} max={60} onChange={(e)=>setQtd(e.target.value)}/>
          {console.log(qtd)}
          <button type="submit" onClick={()=> setNumbers(mega(parseInt(qtd)))}>Sortear</button>
      </main>

    </div>
  )
}
